#! /usr/bin/env python
#extracts the densities of the material from a lammps screen file and plots data

import subprocess
import matplotlib.pyplot as plt

#open data file, read lines, create start and stop flags, and make data arrays
screenFile = open('screen.0','r')
lines = screenFile.readlines()
startFlag = False
stopFlag = False
timestep = []
density = []
for line in lines:
    if "Step Temp Press" in line:
        startFlag = True
    elif startFlag == False and stopFlag == False:
        trash = line
    elif startFlag == True and stopFlag == False:
        timestep.append(int(line.lstrip().split()[0])/2)
        density.append(float(line.lstrip().split()[4])*1000)
    elif startFlag == True and stopFlag == True:
        trash =line


plt.plot(timestep,density,color='k')
plt.xlabel('Time (fs)')
plt.ylabel('Density (kg/m^3)')
plt.show()

